prona-p4-learning-platform/learn-sdn-hub

backend/src/providers/LocalVMProvider.ts

added support to change ssh port of vm/p4 host, addressing issue #20

---

frontend/src/components/Terminal.tsx

Small change to enlarge the terminal. Scrollbar is also displayed now and terminal wraps lines exactly at boundary. Could be improved further in the future to include more features of xterm.js maybe. Addresses #33

enlarge terminal size

---

backend/src/P4Environment.ts
backend/src/consoles/SSHConsole.ts
backend/src/database/MemoryPersister.ts
backend/src/filehandler/SSHFileHandler.ts
backend/src/providers/LocalVMProvider.ts
backend/src/providers/Provider.ts
backend/src/routes/environment.ts
frontend/src/components/EditorTabs.tsx
frontend/src/components/TabControl.tsx
frontend/src/components/Terminal.tsx
frontend/src/main.css
frontend/src/views/AssignmentOverview.tsx
frontend/src/views/Environment.tsx

Initially I wanted to test multiple languages/lsp backends in monaco, but I came across ssh/sftp terminations again. Hence, fixed debugged leaking ssh, sftp and ws connections and added proper undeployment/deletion of assignments/environments incl stateful display of active deployments, 
fixed terminal height (again)
fixed several html warnings to be able to better debug lost connections of websocket lsp frontend and backend conn. I'm still working on debugging the lsp conn, since I want to be able to show it again. It worked in ~50% of the time, and I found some issues in monaco-languageclient and never releases probably fxing the issue, but this included several modifications and package updates etc. that I currently still struggle with, hence I decided to provide a separate branch and …

fixed leaking ssh/sftp/ws conns, added deletion/undeploy of envs, fixed terminal height and html warnings

---

backend/src/Configuration.ts
backend/src/P4Environment.ts
backend/src/consoles/SSHConsole.ts
backend/src/database/MemoryPersister.ts
backend/src/database/MongoDBPersister.ts
backend/src/database/Persister.ts
backend/src/filehandler/SSHFileHandler.ts
backend/src/providers/OpenStackProvider.ts
backend/src/routes/environment.ts
backend/src/typings/pkgcloud/index.d.ts
frontend/package-lock.json
frontend/src/main.css
frontend/src/views/Environment.tsx

implementation of tests in assignments using SSH commands and regexp search in terminal input/output. Tests are organized in steps, that can optionally be configured in Configuration.ts for assignments. If tests in a step are successfull, assignment test will move to the next step, otherwise hints can be given regarding the error. After all steps are successfull, assignment can be submitted, i.e., files of the assignment being uploaded to the backend. Submission files and commands can be configured in assignements in Configuration.ts.

Implement test steps for given lab tasks

---

backend/src/Configuration.ts
backend/src/filehandler/SSHFileHandler.ts

fixes unhandled error/exception that could occasionally happen when deploying files

fix-occasional-sftp-backend-exception

---

backend/src/P4Environment.ts
backend/src/providers/DockerProvider.ts
backend/src/routes/environment.ts

fixed backend exiting when assignment list is empty, fixed backend existing when undeploying an already removed instance

Fix crashes on undeploy and empty assignment list

---

backend/src/P4Environment.ts
backend/src/database/MemoryPersister.ts
backend/src/database/MongoDBPersister.ts
frontend/src/components/Terminal.tsx
package-lock.json

fixed error making already pruned envs impossible to delete, reduce logging output of submission retrieval to silence log during continuous assignment list refresh, add temp log for terminal unmount

fixed deletion of already pruned envs

---

backend/src/Configuration.ts
backend/src/Environment.ts
backend/src/authentication/AuthenticationProvider.ts
backend/src/authentication/MongoDBAuthenticationProvider.ts
backend/src/authentication/PlaintextAuthenticationProvider.ts
backend/src/authentication/PlaintextMultiuserAuthenticationProvider.ts
backend/src/database/MemoryPersister.ts
backend/src/database/MongoDBPersister.ts
backend/src/database/Persister.ts
backend/src/providers/DockerProvider.ts
backend/src/providers/OpenStackProvider.ts
backend/src/routes/environment.ts
backend/src/websocket/ConsoleHandler.ts
backend/src/websocket/LanguageServerHandler.ts
examples/Configuration.ts
frontend/src/views/AssignmentOverview.tsx

- allow users to undeploy group envs directly, improving deadlocks when single users in group forget to undeploy the environment
- clean undeploy on instance deletion by provider, instances are no longer simply deleted anymore
- refactored P4Environment to Environment, better fit as P4 is not the only focus for the environment anymore

improved undeployment of environments

---

Dockerfile
frontend/src/components/FileEditor.tsx
frontend/src/views/AssignmentOverview.tsx

fixed handling of convergence url env var, added editorWorker to dist in Dockerfile - needs to be handled by build/bundler in the future

fixed handling of convergence url env var, added editorWorker to dist

---

backend/src/filehandler/SSHFileHandler.ts
backend/src/websocket/ConsoleHandler.ts
backend/src/websocket/LanguageServerHandler.ts
frontend/package.json
frontend/src/components/FileEditor.tsx
package-lock.json

deactivated local persistence, bumped monaco-collab-ext to support hovering tooltips, deactivated debug log output from backend

deactivated local persistence, bumped monaco-collab-ext

---

Dockerfile
frontend/package.json
frontend/src/views/Environment.tsx
package-lock.json

improved copying of monaco worker dist files, needs to be moved to bundle in the future, bumped mermaid to ensure proper build of learn-sdn-hub container image with recent mermaid versions

improved copying of monaco worker dist files, bumped mermaid

---

frontend/src/views/AssignmentOverview.tsx

fixed convergence collaboration errors related to buggy IndexDB offline storage in browser, need to move from convergence to yjs or something similar anyway as it seams
convergence seams to be discontinued since march 2023? Maybe individually developed further?

Fix convergence ghost documents

---

backend/src/authentication/MongoDBAuthenticationProvider.ts
backend/src/database/Persister.ts
backend/src/routes/environment.ts

added support to configure assignment filter in the db instead of only env var, db filter precedes env var, fixed exception in backend if submissions for user or group cannot be retrieved

added support to configure assignment filter in the db

---

backend/src/Environment.ts
backend/src/authentication/MongoDBAuthenticationProvider.ts
backend/src/providers/FirecrackerProvider.ts
backend/src/routes/environment.ts
frontend/src/api/Request.ts
frontend/src/views/Environment.tsx

Fixed test result not being handled correctly, also changed status code to reflect whether the test was executed correctly (HTTP status code >= 200 && <300) regardless of whether the tests have passed (>= 200 && <251 now) or failed (>=251 now)

Fix test request body and status code handling

---

backend/src/Configuration.ts
backend/src/Environment.ts
backend/src/providers/DockerProvider.ts
backend/src/providers/FirecrackerProvider.ts
backend/src/providers/Provider.ts
backend/src/providers/ProxmoxProvider.ts
examples/sample-firecracker-backend.sh
examples/sample-firecracker-bridge-remove.sh
examples/sample-firecracker-bridge-setup.sh
examples/sample-firecracker-cleanup.sh
examples/sample-proxmox-backend.sh

* added example config for proxmox and firecracker provider
* new assignment demo for proxmox and kommprot labs
* fixed ssh connection testing and ip/gw substitution
* added options (named parameters) to instance provider createServer function

174 proxmox provider fixes

---

backend/src/consoles/SSHConsole.ts
backend/src/filehandler/SSHFileHandler.ts

fix ssh jumphost conn leak

---

frontend/src/components/FileEditor.tsx
frontend/src/components/Terminal.tsx
frontend/src/views/Environment.tsx

Fixed firefox websocket connection lag, moved cursor to correct position after terminal restore

Fix firefox webocket lag

---

backend/src/Environment.ts
backend/src/websocket/LanguageServerHandler.ts
frontend/src/components/FileEditor.tsx

added support for lsp connection over SSH jumphost

---

backend/src/Environment.ts
backend/src/consoles/SSHConsole.ts
backend/src/filehandler/SSHFileHandler.ts
backend/src/providers/Provider.ts
backend/src/providers/ProxmoxProvider.ts
backend/src/routes/environment.ts
frontend/src/views/Assignments.tsx

- support proxmox nodes being temporarily down
- ensured proper cleanup of consoles and ssh connections
- removed debug console log output
- ensured unique id and ip address for proxmox instances
- proper error and connection sharing in sftp file handler

support proxmox nodes being temporarily down, ensured proper cleanup of consoles and ssh connections

---

backend/src/filehandler/SSHFileHandler.ts
backend/src/providers/ProxmoxProvider.ts
backend/src/websocket/LanguageServerHandler.ts

* fixed lsp conn leak when using jumphost
* improved error output for sftp file transfers and proxmox provider template search

fixed lsp conn leak when using jumphost
